services:

  mysql_db:
    image: mysql:8.0
    container_name: memo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - memo_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  django:
    build: .
    container_name: memo_django
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql_db
      DB_PORT: 3306
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    depends_on:
      mysql_db:
        condition: service_healthy

volumes:
  memo_mysql_data: