# Generated by Django 5.2.12 on 2026-03-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('intentos_max', models.SmallIntegerField()),
                ('tiempo_limite', models.SmallIntegerField()),
                ('filas', models.SmallIntegerField(default=4)),
                ('columnas', models.SmallIntegerField(default=4)),
            ],
            options={
                'db_table': 'Categorias_Juego',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('puntaje_min', models.IntegerField(default=0)),
                ('puntaje_max', models.IntegerField()),
                ('orden', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Rangos',
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_id', models.SmallIntegerField()),
                ('nombre_carta', models.CharField(max_length=50)),
                ('ruta_imagen', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='juego.categoriajuego')),
            ],
            options={
                'db_table': 'Cartas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo_electronico', models.CharField(max_length=100, unique=True)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('rango', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='juego.rango')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_sesion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre_sesion', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_sesion', models.TimeField(blank=True, null=True)),
                ('hora_cierre_sesion', models.TimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion', to='juego.usuario')),
            ],
            options={
                'db_table': 'Sesion',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Ganada', 'Ganada'), ('Perdida', 'Perdida'), ('Abandonada', 'Abandonada')], max_length=10)),
                ('tiempo_jugado', models.SmallIntegerField(default=0)),
                ('movimientos', models.SmallIntegerField(default=0)),
                ('intentos_realizados', models.SmallIntegerField(default=0)),
                ('puntaje', models.IntegerField(default=0)),
                ('fecha_partida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partidas', to='juego.categoriajuego')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='juego.usuario')),
            ],
            options={
                'db_table': 'Partida',
            },
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_partidas', models.IntegerField(default=0)),
                ('total_victorias', models.IntegerField(default=0)),
                ('total_derrotas', models.IntegerField(default=0)),
                ('total_abandonadas', models.IntegerField(default=0)),
                ('puntaje_acumulado', models.IntegerField(default=0)),
                ('promedio_tiempo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria_mas_jugada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='juego.categoriajuego')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='juego.usuario')),
            ],
            options={
                'db_table': 'Estadisticas_Jugador',
            },
        ),
    ]
