# Generated by Django 5.2.12 on 2026-03-24 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('registro', 'Registro'), ('recuperacion', 'Recuperación')], max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_otp', to='juego.usuario')),
            ],
            options={
                'db_table': 'CodigoOTP',
            },
        ),
    ]
